###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: 'mysql:5.7'
        container_name: jwt-mysql
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=db_jwt
            - MYSQL_USER=secret
            - MYSQL_PASSWORD=secret
        ports:
            - '31002:3306'

    webserver:
        image: 'nginx:alpine'
        container_name: jwt-webserver
        working_dir: /application
        volumes:
            - './api:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '31000:80'

    php-fpm:
        build: 
            phpdocker/php-fpm
        container_name: jwt-php-fpm
        working_dir: /application
        volumes:
            - './api:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
